version: "3.1"
networks:
  mired:
services:
  mysqlserver2:
    image: flabiusxd/ips:srvmysql
    ports:
      - 3306:3306
    volumes:
      - C:/docker-compose/script:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mired
  phpserver2:
    image: flabiusxd/ips:srvapache
    networks:
      - mired
    ports:
      - 9090:80